name: Publish NPM Alpha Package

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  publish-npm-alpha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short SHA
        id: set_sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: "phips28/gh-action-bump-version@master"
        with:
          default: prerelease
          minor-wording: "MINOR RELEASE"
          major-wording: "MAJOR RELEASE"
          patch-wording: "PATCH RELEASE"
          rc-wording: null
          preid: ${{ format('alpha-{0}', env.SHA_SHORT) }}
          skip-tag: "true"
          skip-commit: "true"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm publish --access public --ignore-scripts --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
